# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15bb622a2635767e5e6814eaadd81e4f6d22420505186a89c5878046b2b360ecce8a8661e8deb00272f3f93889dc71fa305510f284d0ee6ae1ccda8ba1e75f79

test:
  secret_key_base: af8eb2b8ea79776850573186be84d53d629337bf4f629446595b5832adfea78a6652a3e09a1be4b69d5b9d0ebb7406220de7f5fad26c05f872716b0b2a61bbe4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
